sudo: false
dist: trusty
language: ruby
addons:
  apt:
    sources:
      - augeas
    packages:
      - libaugeas-dev

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.3
    env: BUNDLE_PATH=".bundle/gems" CHECK="spec"

script:
  - CHECK=${CHECK} ./.travis/script.sh
