sudo: false
dist: trusty
language: ruby
addons:
  apt:
    sources:
      - augeas
    packages:
      - libaugeas-dev

before_install:
  - rm -f Gemfile.lock
  - rm -rf .bundle/
  - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  - cd ~/.rbenv && src/configure && make -C src
  - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  - . ~/.bashrc && mkdir -p "$(rbenv root)"/plugins && git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
  - . ~/.bashrc && rbenv install -f 2.4.3
  - . ~/.bashrc && rbenv global 2.4.3 && gem install --no-document bundler rake && gem update --system --no-document

install:
  - ./.travis/install.sh
  - bundle config
  - ruby -v

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.3
    env: BUNDLE_PATH=".bundle/gems" CHECK="spec"

script:
  - CHECK=${CHECK} ./.travis/script.sh
